import { Box, Flex, Grid, GridItem } from '@chakra-ui/react';
import React from 'react';

import type { Log } from 'types/api/log';

import { route } from 'nextjs-routes';

import { space } from 'lib/html-entities';
import { decodePrecompileData } from 'lib/inferences/precompile';
import { Alert } from 'toolkit/chakra/alert';
import { Link } from 'toolkit/chakra/link';
import { Skeleton } from 'toolkit/chakra/skeleton';
import { Tag } from 'toolkit/chakra/tag';
import { Tooltip } from 'toolkit/chakra/tooltip';
import CopyToClipboard from 'ui/shared/CopyToClipboard';
import HashStringShorten from 'ui/shared/HashStringShorten';
import IconSvg from 'ui/shared/IconSvg';

import InferenceInput from './InferenceInput';
import InferenceOutput from './InferenceOutput';

type Props = Log & {
  type: 'address' | 'transaction';
  isLoading?: boolean;
};

// Field descriptions for inference parameters
const fieldDescriptions: Record<string, string> = {
  inferenceID: 'Unique identifier for this inference request',
  mode: 'The inference mode used (e.g., streaming, batch)',
  modelCID: 'Content identifier for the ML model stored on Walrus',
  inputData: 'The input data provided to the model',
  output: 'The output generated by the model',
};

const RowHeader = ({ children, isLoading, tooltip }: { children: React.ReactNode; isLoading?: boolean; tooltip?: string }) => (
  <GridItem
    _notFirst={{ mt: { base: 4, lg: 0 } }}
    display="flex"
    alignItems={{ base: 'flex-start', lg: 'center' }}
    py={{ base: 0, lg: 2 }}
  >
    <Flex
      alignItems="center"
      gap={ 2 }
      px={ 3 }
      py={ 1.5 }
      borderRadius="md"
      bgColor={{ _light: 'blackAlpha.50', _dark: 'whiteAlpha.50' }}
    >
      <Skeleton
        fontWeight={ 600 }
        fontSize="sm"
        color={{ _light: 'gray.700', _dark: 'gray.200' }}
        loading={ isLoading }
        textTransform="uppercase"
        letterSpacing="0.02em"
      >
        { children }
      </Skeleton>
      { tooltip && !isLoading && (
        <Tooltip content={ tooltip }>
          <Box
            as="span"
            display="inline-flex"
            alignItems="center"
            justifyContent="center"
            cursor="pointer"
            transition="all 0.2s ease"
            _hover={{ transform: 'scale(1.1)' }}
          >
            <IconSvg
              name="info"
              boxSize={ 3.5 }
              color={{ _light: 'gray.500', _dark: 'gray.400' }}
              _hover={{ color: { _light: 'blue.500', _dark: 'blue.300' } }}
              flexShrink={ 0 }
            />
          </Box>
        </Tooltip>
      ) }
    </Flex>
  </GridItem>
);

const InferenceItem = ({ type, address, preCompileData, decoded, isLoading }: Props) => {

  const renderGridItems = () => {
    const precompileDecodedData = decodePrecompileData(preCompileData);

    return (
      <>
        { precompileDecodedData && (
          <>
            <RowHeader isLoading={ isLoading } tooltip={ fieldDescriptions.inferenceID }>
              Inference ID
            </RowHeader>
            <GridItem display="flex" alignItems="center" py={ 2 }>
              <Box fontSize="sm" fontFamily="mono" color={{ _light: 'gray.800', _dark: 'gray.100' }}>
                <Tag>
                  <HashStringShorten hash={ precompileDecodedData.inferenceID } type="long"/>
                </Tag>
              </Box>
            </GridItem>

            <RowHeader isLoading={ isLoading } tooltip={ fieldDescriptions.mode }>
              Mode
            </RowHeader>
            <GridItem display="flex" alignItems="center" py={ 2 }>
              <Tag>
                { precompileDecodedData.mode }
              </Tag>
            </GridItem>

            <RowHeader isLoading={ isLoading } tooltip={ fieldDescriptions.modelCID }>
              Model CID
            </RowHeader>
            <GridItem display="flex" alignItems="center" py={ 2 }>
              <Flex alignItems="center" gap={ 2 } flexWrap="wrap">
                <Tag>
                  { precompileDecodedData.modelCID }
                </Tag>
                <CopyToClipboard text={ precompileDecodedData.modelCID } isLoading={ isLoading }/>
                <Link
                  href={ `https://walruscan.com/mainnet/blob/${ precompileDecodedData.modelCID }` }
                  external
                  fontSize="sm"
                  fontWeight={ 500 }
                  fontFamily="mono"
                  color={{ _light: 'blue.600', _dark: 'blue.300' }}
                  _hover={{
                    textDecoration: 'underline',
                    color: { _light: 'blue.700', _dark: 'blue.200' },
                  }}
                >
                  View on Walrus
                </Link>
              </Flex>
            </GridItem>

            { precompileDecodedData.request && (
              <>
                <RowHeader isLoading={ isLoading } tooltip={ fieldDescriptions.inputData }>
                  Input Data
                </RowHeader>
                <GridItem display="flex" alignItems="center" py={ 2 }>
                  <Box w="100%" fontSize="sm" fontFamily="mono" color={{ _light: 'gray.800', _dark: 'gray.100' }}>
                    <InferenceInput value={ precompileDecodedData.request } isLoading={ isLoading }/>
                  </Box>
                </GridItem>
              </>
            ) }
          </>
        ) }

        <RowHeader isLoading={ isLoading } tooltip={ fieldDescriptions.output }>
          Output
        </RowHeader>

        <GridItem display="flex" alignItems="center" py={ 2 }>
          { !decoded && !address.is_verified && type === 'transaction' ? (
            <Alert status="warning" display="inline-table" whiteSpace="normal">
              To see accurate decoded input data, the contract must be verified.{ space }
              <Link href={ route({ pathname: '/address/[hash]/contract-verification', query: { hash: address.hash } }) }>Verify the contract here</Link>
            </Alert>
          ) : (
            <Box w="100%" fontSize="sm" fontFamily="mono" color={{ _light: 'gray.800', _dark: 'gray.100' }}>
              { decoded?.parameters.map((param) => (
                <InferenceOutput key={ param.name } value={ param.value } isLoading={ isLoading }/>
              )) }
            </Box>
          ) }
        </GridItem>
      </>
    );
  };

  return (
    <Box
      p={{ base: 4, lg: 6 }}
      borderRadius="xl"
      bgColor={{ _light: 'rgba(255, 255, 255, 0.6)', _dark: 'rgba(255, 255, 255, 0.03)' }}
      border="1px solid"
      borderColor={{ _light: 'gray.100', _dark: 'whiteAlpha.100' }}
      transition="all 0.2s ease"
      _hover={{
        borderColor: { _light: 'gray.200', _dark: 'whiteAlpha.200' },
        boxShadow: { _light: '0 4px 12px rgba(0, 0, 0, 0.05)', _dark: '0 4px 12px rgba(0, 0, 0, 0.2)' },
      }}
      _notFirst={{
        mt: 4,
      }}
    >
      <Grid
        gridTemplateColumns={{ base: 'minmax(0, 1fr)', lg: '180px minmax(0, 1fr)' }}
        gap={{ base: 3, lg: 6 }}
        alignItems={{ base: 'flex-start', lg: 'center' }}
      >
        { renderGridItems() }
      </Grid>
    </Box>
  );
};

export default React.memo(InferenceItem);
