import { Box, Grid, GridItem, Flex } from '@chakra-ui/react';
import React from 'react';

import type { Log } from 'types/api/log';

import { route } from 'nextjs-routes';

import { space } from 'lib/html-entities';
import { Alert } from 'toolkit/chakra/alert';
import { Link } from 'toolkit/chakra/link';
import { Skeleton } from 'toolkit/chakra/skeleton';
import { Tooltip } from 'toolkit/chakra/tooltip';
import IconSvg from 'ui/shared/IconSvg';

import InferenceOutput from './InferenceOutput';
import Item from './layout/Item';
import VStackContainer from './layout/VStackContainer';

// Convert camelCase or snake_case to Title Case with spaces
const formatFieldName = (name: string): string => {
  return name
    // Insert space before capital letters (camelCase)
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    // Replace underscores with spaces (snake_case)
    .replace(/_/g, ' ')
    // Capitalize first letter of each word
    .replace(/\b\w/g, (char) => char.toUpperCase());
};

// Field descriptions for common settlement parameters
const fieldDescriptions: Record<string, string> = {
  batchSize: 'The number of LLM inferences settled and verified in this batch',
  merkleRoot: 'The merkle root hash of the LLM inference results and proofs',
  inputHash: 'The hash of the LLM input data',
  outputHash: 'The hash of the LLM generated response',
  modelInfo: 'Information about the LLM model used for the inference',
  inputData: 'The raw input data provided to the LLM (if public)',
  outputData: 'The raw output data generated by the LLM (if public)',
};

type Props = Log & {
  type: 'address' | 'transaction';
  isLoading?: boolean;
};

const RowHeader = ({ children, isLoading, tooltip }: { children: React.ReactNode; isLoading?: boolean; tooltip?: string }) => (
  <GridItem
    _notFirst={{ mt: { base: 4, lg: 0 } }}
    display="flex"
    alignItems={{ base: 'flex-start', lg: 'center' }}
    py={{ base: 0, lg: 2 }}
  >
    <Flex
      alignItems="center"
      gap={ 2 }
      px={ 3 }
      py={ 1.5 }
      borderRadius="md"
      bgColor={{ _light: 'blackAlpha.50', _dark: 'whiteAlpha.50' }}
    >
      <Skeleton
        fontWeight={ 600 }
        fontSize="sm"
        color={{ _light: 'gray.700', _dark: 'gray.200' }}
        loading={ isLoading }
        textTransform="uppercase"
        letterSpacing="0.02em"
      >
        { children }
      </Skeleton>
      { tooltip && !isLoading && (
        <Tooltip content={ tooltip }>
          <Box
            as="span"
            display="inline-flex"
            alignItems="center"
            justifyContent="center"
            cursor="pointer"
            transition="all 0.2s ease"
            _hover={{ transform: 'scale(1.1)' }}
          >
            <IconSvg
              name="info"
              boxSize={ 3.5 }
              color={{ _light: 'gray.500', _dark: 'gray.400' }}
              _hover={{ color: { _light: 'blue.500', _dark: 'blue.300' } }}
              flexShrink={ 0 }
            />
          </Box>
        </Tooltip>
      ) }
    </Flex>
  </GridItem>
);

const SettlementInferenceItem = ({ type, address, decoded, isLoading }: Props) => {
  const renderGridItems = () => {
    return (
      <>
        { decoded?.parameters && decoded.parameters.length > 0 && (
          <>
            { decoded.parameters.map((param, index) => {
              const displayName = param.name ? formatFieldName(param.name) : `Parameter ${ index + 1 }`;
              const tooltip = param.name ? fieldDescriptions[param.name] : undefined;

              return (
                <React.Fragment key={ param.name || index }>
                  <RowHeader isLoading={ isLoading } tooltip={ tooltip }>
                    { displayName }
                  </RowHeader>
                  <GridItem
                    display="flex"
                    alignItems="center"
                    py={ 2 }
                  >
                    <Box
                      w="100%"
                      fontSize="sm"
                      fontFamily="mono"
                      color={{ _light: 'gray.800', _dark: 'gray.100' }}
                    >
                      <InferenceOutput value={ param.value } isLoading={ isLoading }/>
                    </Box>
                  </GridItem>
                </React.Fragment>
              );
            }) }
          </>
        ) }

        { !decoded && !address.is_verified && type === 'transaction' && (
          <>
            <RowHeader isLoading={ isLoading }>
              Output
            </RowHeader>
            <GridItem py={ 2 }>
              <Alert status="warning" display="inline-table" whiteSpace="normal">
                To see accurate decoded input data, the contract must be verified.{ space }
                <Link href={ route({ pathname: '/address/[hash]/contract-verification', query: { hash: address.hash } }) }>Verify the contract here</Link>
              </Alert>
            </GridItem>
          </>
        ) }

        { !decoded?.parameters && decoded && (
          <>
            <RowHeader isLoading={ isLoading }>
              Data
            </RowHeader>
            <GridItem py={ 2 }>
              <VStackContainer>
                <Item isLoading={ isLoading } isCode>
                  { JSON.stringify(decoded, null, 2) }
                </Item>
              </VStackContainer>
            </GridItem>
          </>
        ) }
      </>
    );
  };

  return (
    <Box
      p={{ base: 4, lg: 6 }}
      borderRadius="xl"
      bgColor={{ _light: 'rgba(255, 255, 255, 0.6)', _dark: 'rgba(255, 255, 255, 0.03)' }}
      border="1px solid"
      borderColor={{ _light: 'gray.100', _dark: 'whiteAlpha.100' }}
      transition="all 0.2s ease"
      _hover={{
        borderColor: { _light: 'gray.200', _dark: 'whiteAlpha.200' },
        boxShadow: { _light: '0 4px 12px rgba(0, 0, 0, 0.05)', _dark: '0 4px 12px rgba(0, 0, 0, 0.2)' },
      }}
      _notFirst={{
        mt: 4,
      }}
    >
      <Grid
        gridTemplateColumns={{ base: 'minmax(0, 1fr)', lg: '180px minmax(0, 1fr)' }}
        gap={{ base: 3, lg: 6 }}
        alignItems={{ base: 'flex-start', lg: 'center' }}
      >
        { renderGridItems() }
      </Grid>
    </Box>
  );
};

export default React.memo(SettlementInferenceItem);
